/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const MatchingLazyImport = createFileRoute('/matching')()
const HomeLazyImport = createFileRoute('/home')()
const Form2LazyImport = createFileRoute('/form2')()
const Form1LazyImport = createFileRoute('/form1')()
const FormLazyImport = createFileRoute('/form')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const MatchingLazyRoute = MatchingLazyImport.update({
  path: '/matching',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/matching.lazy').then((d) => d.Route))

const HomeLazyRoute = HomeLazyImport.update({
  path: '/home',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/home.lazy').then((d) => d.Route))

const Form2LazyRoute = Form2LazyImport.update({
  path: '/form2',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/form2.lazy').then((d) => d.Route))

const Form1LazyRoute = Form1LazyImport.update({
  path: '/form1',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/form1.lazy').then((d) => d.Route))

const FormLazyRoute = FormLazyImport.update({
  path: '/form',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/form.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/form': {
      preLoaderRoute: typeof FormLazyImport
      parentRoute: typeof rootRoute
    }
    '/form1': {
      preLoaderRoute: typeof Form1LazyImport
      parentRoute: typeof rootRoute
    }
    '/form2': {
      preLoaderRoute: typeof Form2LazyImport
      parentRoute: typeof rootRoute
    }
    '/home': {
      preLoaderRoute: typeof HomeLazyImport
      parentRoute: typeof rootRoute
    }
    '/matching': {
      preLoaderRoute: typeof MatchingLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  AboutLazyRoute,
  FormLazyRoute,
  Form1LazyRoute,
  Form2LazyRoute,
  HomeLazyRoute,
  MatchingLazyRoute,
])

/* prettier-ignore-end */
